symplifica:
    resource: "@SymplificaBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
