<?php

namespace SymplificaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HabitacionPacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitacionPacienteRepository extends EntityRepository
{
}
